# Binary sensor
- platform: bayesian
  prior: 0.5
  name: 'Christine Presence'
  probability_threshold: 0.8
  device_class: 'presence'
  observations:
    - entity_id: 'device_tracker.galaxy_s9'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.50_tcl_roku_tv'
      prob_given_true: 0.5
      prob_given_false: 0.5
      platform: 'state'
      to_state: 'home'
    # - entity_id: 'device_tracker.google_maps_107286426735337214006'
    #   prob_given_true: 0.8
    #   prob_given_false: 0.1
    #   platform: 'state'
    #   to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Shankar Presence'
  probability_threshold: 0.8
  device_class: 'presence'
  observations:
    - entity_id: 'device_tracker.pixel_2'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.shankars_air'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.40_4e_36_8b_10_d4'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.50_tcl_roku_tv'
      prob_given_true: 0.5
      prob_given_false: 0.5
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.pop_os'
      prob_given_true: 0.6
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'home'

    # - entity_id: 'device_tracker.google_maps_100911281029769970893'
    #   prob_given_true: 0.7
    #   prob_given_false: 0.2
    #   platform: 'state'
    #   to_state: 'home'
# - platform: rest
#   name: 'Nexus Motion'
#   resource: http://10.0.0.4:8080/sensors.json?sense=motion_active
#   value_template: '{{ value_json.motion_active.data[0][1][0] | round(0) }}'
#   # sensor_class: motion

# front camera motion sensor
- platform: template
  sensors:
    motion_front:
      friendly_name: Front Camera
      device_class: motion
      value_template: "{{ is_state('camera.front', 'motion') }}"
      delay_off:
        seconds: 120
# back camera motion sensor
- platform: template
  sensors:
    motion_back:
      friendly_name: back Camera
      device_class: motion
      value_template: "{{ is_state('camera.back', 'motion') }}"
      delay_off:
        seconds: 120
- platform: ping
  name: Router Ping
  host: 192.168.88.1
  count: 2
  scan_interval: 120
- platform: ping
  name: Upstairs WAP Ping
  host: 192.168.88.6
  count: 2
  scan_interval: 120
- platform: ping
  name: Downstairs WAP Ping
  host: 192.168.88.5
  count: 2
  scan_interval: 120
- platform: ping
  name: Switch Ping
  host: 192.168.88.4
  count: 2
  scan_interval: 120
- platform: ping
  name: Front Camera Ping
  host: 192.168.88.15
  count: 2
  scan_interval: 120
- platform: ping
  name: Back Camera Ping
  host: 192.168.88.16
  count: 2
  scan_interval: 120
- platform: workday
  country: US
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2021-01-01'
    - '2021-04-02'
    - '2021-05-31'
    - '2021-06-05'
    - '2021-09-06'
    - '2021-11-25'
    - '2021-12-24'
    - '2021-12-27'
    - '2021-12-28'
    - '2021-12-29'
    - '2021-12-30'
    - '2021-12-31'
