homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.96874
  longitude: -77.03393
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 78
  # metric for Metric, imperial for Imperial
  unit_system: Metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# logger:
#   default: debug

frontend:
  themes: !include themes.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# Discover some devices automatically
discovery:

google_location:

device_tracker:
  - platform: google_location
    username: !secret google_username
    password: !secret google_password
    max_gps_accuracy: 200

# darksky
sensor:
  - platform: darksky
    api_key: !secret darksky_api
    longitude: -77.033961
    latitude: 38.968746
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 6
      - 12
      - 18
      - 24
      - 30
      - 36
      - 42
      - 48
    monitored_conditions:
      - temperature
      - apparent_temperature
      - nearest_storm_distance
      - nearest_storm_bearing
      - wind_speed
      - wind_gust
      - wind_bearing
      - cloud_cover
      - precip_probability
      - precip_type
      - precip_intensity
    scan_interval:
      minutes: 2
  - platform: systemmonitor
    resources:
      # - type: disk_use_percent
      #   arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  
upnp:
  sensors: false
  port_mapping: false

# Text to speech
tts:
  - platform: google_translate


no_ip:
  domain: !secret noip_domain
  username: !secret noip_username
  password: !secret noip_password

matrix:
  homeserver: https://matrix.org
  username: !secret matrix_username
  password: !secret matrix_password
  rooms:
    - "!RZInnssIgfBYMGRmtY:matrix.org"
    - "!kgrzdnIkVTmRcWQVWK:matrix.org"
  commands:
    - word: testword
      name: testword

signalmessenger:

notify:
  - name: matrix_notify
    platform: matrix
    default_room: "!kgrzdnIkVTmRcWQVWK:matrix.org"
  - name: twitter_notify
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret
  - name: signal_notify
    platform: signalmessenger
    sender_nr: !secret signal_sender_number
    recp_nr: !secret signal_receiver_number
    signal_cli_path: /usr/local/bin
    signal_conf_path: /home/homeassistant/.local/share/signal-cli
  # - name: signal_group_notify
  #   platform: signalmessenger
  #   sender_nr: !secret signal_sender_number
  #   group: !secret signal_group_id
  #   signal_cli_path: /usr/local/bin
  #   signal_conf_path: /home/homeassistant/.local/share/signal-cli

hello_state:

hello_service:

# speedtest
speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload

sun:
  elevation: 87

# fastdotcom:
#   scan_interval:
#     minutes: 120


# android ip camera
# camera:
#   - platform: mjpeg
#     mjpeg_url: http://10.0.0.4:8080/video

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
