homeassistant:
  name: Home
  latitude: 38.96874
  longitude: -77.03393
  elevation: 78
  unit_system: Metric
  time_zone: America/New_York
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp
    - /home/homeassistant
    - /media/usb

# logger:
#   default: debug


frontend:
  themes: !include themes.yaml
  # themes: !include_dir_merge_named themes

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   ip_ban_enabled: true
#   login_attempts_threshold: 3
#   base_url: wolverines.duckdns.org
#   ssl_certificate: /etc/letsencrypt/live/wolverines.duckdns.org/fullchain.pem
#   ssl_key: /etc/letsencrypt/live/wolverines.duckdns.org/privkey.pem

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# {
#   "lets_encrypt": {
#     "accept_terms": true,
#     "certfile": "fullchain.pem",
#     "keyfile": "privkey.pem"
#   },
#   "token": !secret duckdns_token,
#   "domains": [!secret duckdns_domain],
#   "seconds": 300
# }

# Discover some devices automatically
discovery:

google_location:

device_tracker: !include device_tracker.yaml

# Bayesian Sensors for Home detection for each person
binary_sensor: !include binary_sensor.yaml


upnp:
  sensors: false
  port_mapping: false

# Text to speech
tts:
  - platform: google_translate

# no_ip:
#   domain: !secret noip_domain
#   username: !secret noip_username
#   password: !secret noip_password

matrix:
  homeserver: https://matrix.org
  username: !secret matrix_username
  password: !secret matrix_password
  rooms:
    - "!RZInnssIgfBYMGRmtY:matrix.org"
    - "!kgrzdnIkVTmRcWQVWK:matrix.org"
  commands:
    - word: testword
      name: testword

signalmessenger:

notify:
  - name: matrix_notify
    platform: matrix
    default_room: "!kgrzdnIkVTmRcWQVWK:matrix.org"
  - name: twitter_notify
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret
  - name: signal_notify
    platform: signalmessenger
    sender_nr: !secret signal_sender_number
    recp_nr: !secret signal_receiver_number
    signal_cli_path: /usr/local/bin
    signal_conf_path: /home/homeassistant/.local/share/signal-cli
  # - name: signal_group_notify
  #   platform: signalmessenger
  #   sender_nr: !secret signal_sender_number
  #   group: !secret signal_group_id
  #   signal_cli_path: /usr/local/bin
  #   signal_conf_path: /home/homeassistant/.local/share/signal-cli

# hello_state:

# hello_service:

# speedtest
speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload
  manual: true

sun:
  elevation: 87

# fastdotcom:
#   scan_interval:
#     minutes: 120

# ffmpeg:
#   ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: mjpeg
    mjpeg_url: http://localhost:8081

shell_command:
  renew_ssl: sudo certbot renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

tplink:
  discovery: true

weather:
  - platform: darksky
    api_key: !secret darksky_api

# INCLUDES
sensor: !include sensor.yaml
zone: !include zone.yaml
person: !include person.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
