homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: Metric
  time_zone: America/New_York
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /config
    - /media/camera


lovelace:
  mode: yaml
  resources:
    # - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
    #   type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    # - url: /local/weather-card-chart.js?v=0.0.2
    #   type: module
    # - url: /local/swipe-navigation.js?v=0.0.1
    #   type: module
    # - url: /local/mini-graph-card-bundle.js?v=0.9.4
    #   type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    # - url: /local/battery-state-card.js?v=0.0.1
    #   type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module

    # - url: /local/simple-thermostat.js?v=1
    #   type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module

    # - url: /local/custom-header.js?v=0.0.1
    #   type: module

frontend:
  # themes: !include_dir_merge_named ./themes
  themes: !include ./themes/one_dark_theme.yml


# Configure a default setup of Home Assistant (frontend, api, etc)

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   ip_ban_enabled: true
#   login_attempts_threshold: 2
#   base_url: wolverines.duckdns.org
#   ssl_certificate: ssl/fullchain.pem
#   ssl_key: ssl/privkey.pem

default_config:

recorder:
  auto_purge: true
  purge_keep_days: 366
  db_url: mysql://homeassistant:2PtZXpJDDjSGsv@127.0.0.1:3306/homeassistant?charset=utf8

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token


# Discover some devices automatically
discovery:


device_tracker: !include device_tracker.yaml

# Bayesian Sensors for Home detection for each person
binary_sensor: !include binary_sensor.yaml


# Text to speech
tts:
  - platform: google_translate

# Alarm
alarm_control_panel:
  - platform: manual
    name: "HA Alarm"
    code: "1234"
    code_arm_required: true
    delay_time: 10
    arming_time: 30
    trigger_time: 30
    disarm_after_trigger: false

# no_ip:
#   domain: !secret noip_domain
#   username: !secret noip_username
#   password: !secret noip_password

ecobee:
  api_key: !secret ecobee_api_key

# matrix:
#   homeserver: https://matrix.org
#   username: !secret matrix_username
#   password: !secret matrix_password
#   rooms:
#     - "!RZInnssIgfBYMGRmtY:matrix.org"
#     - "!kgrzdnIkVTmRcWQVWK:matrix.org"
#   commands:
#     - word: testword
#       name: testword

# signalmessenger:

notify:
  # - name: matrix_notify
  #   platform: matrix
  #   default_room: "!kgrzdnIkVTmRcWQVWK:matrix.org"
  - name: twitter_notify
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret
  - name: signal
    platform: signal_messenger
    url: "http://localhost:8080"
    number: !secret signal_rpi_number
    recipients: 
      - !secret signal_rpi_recipient
  - name: signal_group
    platform: signal_messenger
    url: "http://localhost:8080"
    number: !secret signal_rpi_number
    recipients:
      - !secret signal_rpi_group
  - name: ecobee_notify
    platform: ecobee
  # - name: signal_notify
  #   platform: signalmessenger
  #   sender_nr: !secret signal_sender_number
  #   recp_nr: !secret signal_receiver_number
  #   signal_cli_path: /usr/local/bin
  #   signal_conf_path: /home/homeassistant/.local/share/signal-cli
  # - name: signal_group_notify
  #   platform: signalmessenger
  #   sender_nr: !secret signal_sender_number
  #   group: !secret signal_group_id
  #   signal_cli_path: /usr/local/bin
  #   signal_conf_path: /home/homeassistant/.local/share/signal-cli

# hello_state:

# hello_service:

# speedtest
speedtestdotnet:
  scan_interval:
    hours: 24
  monitored_conditions:
    - ping
    - download
    - upload
  manual: false

sun:
  elevation: !secret home_elevation

# fastdotcom:
#   scan_interval:
#     minutes: 120

# ffmpeg:
#   ffmpeg_bin: /usr/bin/ffmpeg

camera:
  # - platform: mjpeg
  #   mjpeg_url: http://localhost:8081
  # - platform: generic
  #   name: front
  #   still_image_url: !secret front_image_url
  #   stream_source: !secret front_source_low_url
  - platform: reolink_dev
    host: !secret front_ip
    username: !secret front_username
    password: !secret front_password
    name: front
    stream: main # or sub
    protocol: rtmp # or rtsp
    channel: 0
    scan_interval: 5
  - platform: reolink_dev
    host: !secret back_ip
    username: !secret back_username
    password: !secret back_password
    name: back
    stream: main # or sub
    protocol: rtmp # or rtsp
    channel: 0
    scan_interval: 5
  - platform: generic
    still_image_url: https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/usfcx/current.png
    name: Radar DC Current
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=40&type=N0R&mapx=400&mapy=240&brand=wui&delay=25&frame=0&scale=1&transx=-895.5319148936169&transy=895.5319148936169&severe=1&smooth=0&centerx=-495.5319148936169&centery=1135.5319148936169&station=LWX&rainsnow=0&lightning=0&noclutter=1&showlabels=1&showstorms=5&rand=26610482
    name: Radar DC Animated

shell_command:
  renew_ssl: sudo certbot renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

# weather:
#   - platform: openweathermap
#     api_key: !secret openweathermap_api
  # - platform: nws
  #   api_key: !secret nws_api
  #   longitude: !secret home_longitude
  #   latitude: !secret home_latitude
  #   mode: hourly
  #   station: !secret nws_station
  #   name: Weather
    
# google calendar
google:
  client_id: !secret google_calendar_clientid
  client_secret: !secret google_calendar_clientsecret
  track_new_calendar: false

circadian_lighting:

# monitor docker
monitor_docker:
  - name: Docker


lifx:
  light:
    - broadcast: 192.168.200.50
    - broadcast: 192.168.200.51
    - broadcast: 192.168.200.52
    - broadcast: 192.168.200.53
    - broadcast: 192.168.200.54

tplink:
  switch:
    - host: 192.168.200.60

utility_meter:
  solar_hourly_energy:
    source: sensor.solar_energy
    cycle: hourly
  solar_daily_energy:
    source: sensor.solar_energy
    cycle: daily
  solar_weekly_energy:
    source: sensor.solar_energy
    cycle: weekly
  solar_monthly_energy:
    source: sensor.solar_energy
    cycle: monthly
  solar_yearly_energy:
    source: sensor.solar_energy
    cycle: yearly


light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.sconce_1
      - light.sconce_2
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedroom_lamp
  - platform: group
    name: Downstairs Lights
    entities:
      - light.sconce_1
      - light.sconce_2
      - light.dining_room_lamp
      - light.hallway
  - platform: group
    name: Exterior
    entities:
      - light.porch
  - platform: group
    name: Upstairs Lights
    entities:
      - light.bedroom_lamp
      - light.lamp
  - platform: group
    name: Notification Lights
    entities:
      - light.downstairs_lights
      - light.upstairs_lights
  - platform: wiz_light
    name: porch
    host: 192.168.200.45
  - platform: wiz_light
    name: hallway
    host: 192.168.200.46

# mikrotik:
#   - name: Mikrotik
#     host:  !secret mikrotik_host
#     port: 8728
#     arp_ping: false
#     force_dhcp: false
#     detection_time: 30 # seconds before device is marked away
#     username: !secret mikrotik_username
#     password: !secret mikrotik_password

# INCLUDES
sensor: !include sensor.yaml
zone: !include zone.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml

# DEPRECATED SHIT
# google_location:
