homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: Metric
  time_zone: America/New_York
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /media/usb


lovelace:
  mode: yaml
  resources:
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module

frontend:
  # themes: !include_dir_merge_named ./themes
  themes: !include ./themes/one_dark_theme.yml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  http:
    ip_ban_enabled: true
    login_attempts_threshold: 3
    base_url: wolverines.duckdns.org
    ssl_certificate: /etc/letsencrypt/live/wolverines.duckdns.org/fullchain.pem
    ssl_key: /etc/letsencrypt/live/wolverines.duckdns.org/privkey.pem

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# {
#   "lets_encrypt": {
#     "accept_terms": true,
#     "certfile": "fullchain.pem",
#     "keyfile": "privkey.pem"
#   },
#   "token": !secret duckdns_token,
#   "domains": [!secret duckdns_domain],
#   "seconds": 300
# }

# Discover some devices automatically
discovery:


device_tracker: !include device_tracker.yaml

# Bayesian Sensors for Home detection for each person
binary_sensor: !include binary_sensor.yaml

# Text to speech
tts:
  - platform: google_translate

# no_ip:
#   domain: !secret noip_domain
#   username: !secret noip_username
#   password: !secret noip_password

matrix:
  homeserver: https://matrix.org
  username: !secret matrix_username
  password: !secret matrix_password
  rooms:
    - "!RZInnssIgfBYMGRmtY:matrix.org"
    - "!kgrzdnIkVTmRcWQVWK:matrix.org"
  commands:
    - word: testword
      name: testword

# signalmessenger:

notify:
  - name: matrix_notify
    platform: matrix
    default_room: "!kgrzdnIkVTmRcWQVWK:matrix.org"
  - name: twitter_notify
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret
  # - name: signal_notify
  #   platform: signalmessenger
  #   sender_nr: !secret signal_sender_number
  #   recp_nr: !secret signal_receiver_number
  #   signal_cli_path: /usr/local/bin
  #   signal_conf_path: /home/homeassistant/.local/share/signal-cli
  # - name: signal_group_notify
  #   platform: signalmessenger
  #   sender_nr: !secret signal_sender_number
  #   group: !secret signal_group_id
  #   signal_cli_path: /usr/local/bin
  #   signal_conf_path: /home/homeassistant/.local/share/signal-cli

# hello_state:

# hello_service:

# speedtest
speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload
  manual: true

sun:
  elevation: 87

# fastdotcom:
#   scan_interval:
#     minutes: 120

# ffmpeg:
#   ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: mjpeg
    mjpeg_url: http://localhost:8081
  - platform: generic
    still_image_url: https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/usfcx/current.png
    name: Radar DC Current
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=40&type=TR0&mapx=400&mapy=240&brand=wui&delay=15&frame=0&scale=1&transx=-856&transy=-296&severe=1&smooth=0&centerx=-456&centery=-56&station=IAD&rainsnow=1&lightning=0&noclutter=0&showlabels=1&showstorms=0&rand=26609628
    name: Radar DC Animated

shell_command:
  renew_ssl: sudo certbot renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api
  # - platform: nws
  #   api_key: !secret nws_api
  #   longitude: !secret home_longitude
  #   latitude: !secret home_latitude
  #   mode: hourly
  #   station: !secret nws_station
  #   name: Weather
    

# INCLUDES
sensor: !include sensor.yaml
zone: !include zone.yaml
# person: !include person.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# DEPRECATED SHIT
# google_location:
