# Front camera switches
- platform: template
  switches:
    camera_front_email:
      value_template: "{{ is_state_attr('camera.front', 'email_enabled', true) }}"
      turn_on:
        service: camera.enable_email
        data:
          entity_id: camera.front
      turn_off:
        service: camera.disable_email
        data:
          entity_id: camera.front
      icon_template: >-
        {% if is_state_attr('camera.front', 'email_enabled', true) %}
          mdi_email
        {% else %}
          mdi_email-outline
        {% endif %}
