title: Tablet
views:
  - panel: true
    icon: 'mdi:home'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: alarm-panel
                states:
                  - arm_home
                  - arm_away
                entity: alarm_control_panel.alarm
              - type: horizontal-stack
                cards:
                  - type: picture-glance
                    title: front
                    camera_image: camera.front
                    entities: 
                      - entity: binary_sensor.motion_front
                        tap_action: 
                          action: call-service
                          service: script.turn_on
                          service_data:
                            entity_id: script.front_camera_signal_motion

                  - type: picture-glance
                    title: back
                    camera_image: camera.back
                    entities: 
                      - entity: binary_sensor.motion_back
                        tap_action: 
                          action: call-service
                          service: script.turn_on
                          service_data:
                            entity_id: script.back_camera_signal_motion
          - type: vertical-stack
            cards:
              - type: weather-forecast
                entity: weather.openweathermap
              - type: entities
                square: false
                show_header_toggle: false
                entities:
                  # - entity: light.upstairs_lights
                  #   name: Upstairs
                  - entity: light.bedroom_lights
                    name: Bedroom
                  - entity: light.downstairs_lights
                    name: Downstairs
                  - entity: light.dining_room_lamp
                    name: Dining Room
                  - entity: light.living_room_lights
                    name: Living Room
                  - entity: light.lamp
                    name: Lamp
                  - entity: light.hallway
                    name: Hallway
                  - entity: light.porch
                    name: Porch
  - title: Cameras
    panel: true
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: front
            camera_image: camera.front
            entities: 
              - entity: binary_sensor.motion_front
                tap_action: 
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.front_camera_signal_motion

          - type: picture-glance
            title: back
            camera_image: camera.back
            entities: 
              - entity: binary_sensor.motion_back
                tap_action: 
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.back_camera_signal_motion


