title: Tablet
views:
  - panel: true
    icon: 'mdi:home'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: alarm-panel
                    states:
                      - arm_home
                      - arm_away
                    entity: alarm_control_panel.alarm
                  - type: grid
                    square: false
                    cards:
                      # - type: light
                      #   entity: light.upstairs_lights
                      - type: light
                        entity: light.bedroom_lights
                        name: Bedroom
                      # - type: light
                      #   entity: light.downstairs_lights
                      - type: light
                        entity: light.dining_room_lamp
                        name: Dining
                      - type: light
                        entity: light.living_room_lights
                        name: Living
                      - type: button
                        entity: switch.downstairs_plug
                      - type: light
                        entity: light.hallway
                      - type: light
                        entity: light.porch
              - type: vertical-stack
                cards:
                  - type: weather-forecast
                    entity: weather.openweathermap
                  - type: horizontal-stack
                    cards:
                      - type: picture-entity
                        title: front
                        entity: camera.front

                      - type: picture-entity
                        title: back
                        entity: camera.back
          - type: horizontal-stack
            cards:
              - type: 'custom:mini-graph-card'
                entities:
                  - entity: sensor.envoy_current_energy_production
                    name: Power
                    show_state: true
                  - entity: sensor.solar_elevation
                    name: Elevation
                    line_width: 1
                    show_fill: false
                    show_state: false
                    y_axis: secondary
                    color: '#666666'
                  - entity: sensor.openweathermap_cloud_coverage
                    name: Cloud Cover
                    line_width: 1
                    show_fill: false
                    show_state: true
                    y_axis: secondary
                hour24: true
                hours_to_show: 48
                points_per_hour: 15
                line_width: 1
                lower_bound_secondary: 0
                # group_by: hour
                show:
                  extrema: true
                  average: true
                  graph: true
                  points: false
                  legend: false
              - type: 'custom:mini-graph-card'
                entities:
                  - entity: sensor.solar_daily_energy
                    name: Daily Energy
                aggregate_func: max
                hour24: true
                hours_to_show: 720
                points_per_hour: 1
                group_by: date
                show:
                  extrema: true
                  average: true
                  graph: bar
  - title: Cameras
    panel: true
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            title: front
            entity: camera.front

          - type: picture-entity
            title: back
            entity: camera.back


