title: Home
custom_header:
  compact_mode: true
  button_text:
    # options: '{{dayNameShort}} {{year4d}}-{{monthNumLZ}}-{{dayNumLZ}}<br>{{ hours24LZ }}:{{ minutesLZ }}'
    options: '{{dayNameShort}} {{monthNameShort}} {{dayNum}}<br>{{hours24LZ}}:{{minutesLZ}}'
swipe_nav:
  wrap: true
  animate: flip
  skip_tabs:
  swipe_amount: 15
views:
  - title: Main
    icon: mdi:home-assistant
    badges:
      - entity: binary_sensor.updater
      - entity: person.shankar_kulumani
      - entity: sensor.solar_angle
      - entity: sensor.ambient_light
      - entity: sensor.period_of_day
      - entity: sensor.waze_home_to_collins
      - entity: sensor.memory_use_percent
      - entity: sensor.ssl_cert_expiry
      - entity: sensor.processor_use
      - entity: sensor.network_in_eth0
      - entity: sensor.speedtest_ping
      - entity: sensor.speedtest_download
      - entity: sensor.speedtest_upload
      - entity: sensor.network_out_eth0
      - entity: sun.sun
    cards:
      - entity: media_player.50_tcl_roku_tv
        type: media-control
      - entities:
        - light.living_room_lamp
        - light.entry_lamp
        - light.bedroom_lamp
        - light.bedroom_ceiling
        - light.bedroom_ceiling_2
        show_header_toggle: true
        title: Lights
        type: entities
      - entity: camera.mjpeg_camera
        type: picture-entity
  - title: Weather
    icon: mdi:flower
    cards:
      - type: weather-forecast
        entity: weather.openweathermap
      - type: weather-forecast
        entity: weather.kcgs_daynight
      - type: picture-entity
        entity: camera.radar_dc_current
      - type: picture-entity
        entity: camera.radar_dc_animated
      - type: 'custom:weather-card-chart'
        title: Weather
        weather: weather.openweathermap
  - title: F1
    icon: mdi:car-sports
    cards:
      - type: markdown
        content: > 
          ## {{ states.calendar.f1_all.attributes.message }}
            
          {{ ((as_timestamp(states.calendar.f1_all.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

          Start local: {{ states.calendar.f1_all.attributes.start_time}} 

          Start UTC: {{ as_timestamp(states.calendar.f1_all.attributes.start_time)|timestamp_utc}} 

          ## {{ states.calendar.f1_qualifying.attributes.message }}
          
          {{ ((as_timestamp(states.calendar.f1_qualifying.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go
          
          Start local: {{ states.calendar.f1_qualifying.attributes.start_time }}

          Start UTC: {{ as_timestamp(states.calendar.f1_qualifying.attributes.start_time)|timestamp_utc }}

          ## {{ states.calendar.f1_race.attributes.message }}
          
          {{ ((as_timestamp(states.calendar.f1_race.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

          Start local: {{ states.calendar.f1_race.attributes.start_time }}

          Start UTC: {{ as_timestamp(states.calendar.f1_race.attributes.start_time)|timestamp_utc }}
      - type: picture
        image: /local/f1.jpg
        tap_action:
          action: navigate
          navigation_path: /lovelace/home



