title: Home
custom_header:
  compact_mode: true
  button_text:
    # options: '{{dayNameShort}} {{year4d}}-{{monthNumLZ}}-{{dayNumLZ}}<br>{{ hours24LZ }}:{{ minutesLZ }}'
    options: '{{dayNameShort}} {{monthNameShort}} {{dayNum}}<br>{{hours24LZ}}:{{minutesLZ}}'
swipe_nav:
  wrap: true
  animate: flip
  skip_tabs:
  swipe_amount: 15
views:
  - title: Main
    icon: mdi:home-assistant
    cards:
      - type: entities
        entities:
          - entity: light.living_room_lights
          - entity: light.exterior_lights
          - entity: light.upstairs_lights
          - entity: light.downstairs_lights
      # - entity: alarm_control_panel.ha_alarm
      #   type: alarm-panel
      #   name: Alarm
      #   states: 
      #     - arm_home
      #     - arm_away
      #     - arm_night
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: thermostat
                entity: climate.downstairs
                name: Downstairs
              - type: thermostat
                entity: climate.upstairs
                name: Upstairs
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: front
            camera_image: camera.front
            entities: 
              - binary_sensor.motion_front
          - type: picture-glance
            title: back
            camera_image: camera.back
            entities: 
              - binary_sensor.motion_back
      - entity: media_player.50_tcl_roku_tv
        type: media-control
  - title: Weather
    icon: mdi:weather-sunny
    cards:
      - type: 'custom:weather-card-chart'
        title: Weather
        weather: weather.openweathermap
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.radar_dc_current
          - type: picture-entity
            entity: camera.radar_dc_animated
      - type: 'custom:mini-graph-card'
        name: Temperature
        entities:
          - sensor.downstairs_temperature
          - sensor.upstairs_temperature
          - sensor.ecobee_outside_temperature
        hours_to_show: 48
        points_per_hour: 10
      - type: 'custom:mini-graph-card'
        name: Humidity
        entities:
          - sensor.downstairs_humidity
          - sensor.upstairs_humidity
          - sensor.ecobee_outside_humidity
        hours_to_show: 48
        points_per_hour: 10
  - title: F1
    icon: mdi:car-sports
    cards:
      - type: vertical-stack
        cards:
        - type: picture
          image: /local/f1.jpg
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.roku_espn_tap_action
          # tap_action:
            # action: call-service
            # service: media_player.select_source
            # service_data:
            #   entity_id: media_player.50_tcl_roku_tv
            #   source: "ESPN"
        - type: markdown
          content: > 
            ## {{ states.calendar.f1_all.attributes.message }}
              
            {{ ((as_timestamp(states.calendar.f1_all.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

            Start local: {{ states.calendar.f1_all.attributes.start_time}} 

            Start UTC: {{ as_timestamp(states.calendar.f1_all.attributes.start_time)|timestamp_utc}} 

            ## {{ states.calendar.f1_qualifying.attributes.message }}
            
            {{ ((as_timestamp(states.calendar.f1_qualifying.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go
            
            Start local: {{ states.calendar.f1_qualifying.attributes.start_time }}

            Start UTC: {{ as_timestamp(states.calendar.f1_qualifying.attributes.start_time)|timestamp_utc }}

            ## {{ states.calendar.f1_race.attributes.message }}
            
            {{ ((as_timestamp(states.calendar.f1_race.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

            Start local: {{ states.calendar.f1_race.attributes.start_time }}

            Start UTC: {{ as_timestamp(states.calendar.f1_race.attributes.start_time)|timestamp_utc }}
  - title: Commute
    icon: mdi:briefcase
    cards:
      - type: sensor
        entity: sensor.waze_home_to_collins
        name: Collins Commute
        graph: line
  - title: System
    icon: mdi:cog
    cards:
      - type: glance
        entities:
          - sensor.ha_uptime
          - sensor.ha_version
      - type: horizontal-stack
        cards:
          - type: 'custom:mini-graph-card'
            align_icon: left
            align_state: center
            entities:
              - sensor.processor_use
            font_size: 75
            icon: 'mdi:chip'
            name: CPU
            show:
              fill: false
          - type: 'custom:mini-graph-card'
            align_icon: left
            align_state: center
            entities:
              - sensor.memory_use_percent
            font_size: 75
            name: Memory
            show:
              fill: false
          - type: 'custom:mini-graph-card'
            align_icon: left
            align_state: center
            entities:
              - sensor.disk_use_percent
            font_size: 75
            name: Data 
            show:
              fill: false
      - type: glance
        entities:
          - sensor.pixel_2_battery_level
          - sensor.pixel_2_battery_state
      - type: horizontal-stack
        cards:
          - type: 'custom:mini-graph-card'
            align_icon: left
            align_state: center
            entities:
              - sensor.pixel_2_battery_level
            font_size: 75
            icon: 'mdi:battery'
            name: Battery
            show:
              fill: false
            hours_to_show: 48
            points_per_hour: 10
      - type: entities
        title: Status
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.duckdns_home
          - sensor.myip



