title: Home
# custom_header:
#   compact_mode: true
#   button_text:
#     # options: '{{dayNameShort}} {{year4d}}-{{monthNumLZ}}-{{dayNumLZ}}<br>{{ hours24LZ }}:{{ minutesLZ }}'
#     options: '{{dayNameShort}} {{monthNameShort}} {{dayNum}}<br>{{hours24LZ}}:{{minutesLZ}}'
# swipe_nav:
#   wrap: true
#   animate: flip
#   skip_tabs:
#   swipe_amount: 15
views:
  - title: Main
    icon: mdi:home-assistant
    cards:
      - type: grid
        square: false
        title: Lights
        cards:
          - type: light
            entity: light.upstairs_lights
            name: Upstairs
          - type: light
            entity: light.downstairs_lights
            name: Downstairs
          - type: light
            entity: light.living_room_lights
            name: Living Room
          - type: light
            entity: light.sconce_1
            name: Sconce 1
          - type: light
            entity: light.sconce_2
            name: Sconce 2
          - type: light
            entity: light.dining_room_lamp
            name: Dining Room
          - type: light
            entity: light.bedroom_lamp
            name: Bedroom
      - type: vertical-stack
        title: Thermostats
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.downstairs
            step_size: 0.1
            decimals: 1
            step_layout: row
            fallback: ' '
            control:
              _names: true
              _headings: false
              hvac: 
                heat_cool: false
              preset: true
          - type: 'custom:simple-thermostat'
            entity: climate.upstairs
            step_size: 0.1
            decimals: 1
            step_layout: row
            fallback: ' '
            control:
              _names: true
              _headings: false
              hvac: 
                heat_cool: false
              preset: true
      - type: vertical-stack
        title: Cameras
        cards:
          - type: picture-glance
            title: front
            camera_image: camera.front
            entities: 
              - binary_sensor.motion_front
          - type: picture-glance
            title: back
            camera_image: camera.back
            entities: 
              - binary_sensor.motion_back
  - title: Weather
    icon: mdi:weather-sunny
    cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.openweathermap
          - type: picture-entity
            entity: camera.radar_dc_current
          - type: picture-entity
            entity: camera.radar_dc_animated
      - type: vertical-stack
        cards:
          - type: 'custom:mini-graph-card'
            name: Temperature
            entities:
              - entity: sensor.downstairs_temperature
                name: Downstairs
                show_state: false
              - entity: sensor.upstairs_temperature
                name: Upstairs
                show_state: false
              - entity: sensor.ecobee_outside_temperature
                name: Outside
                show_state: false
            hours_to_show: 24
            points_per_hour: 10
            line_width: 2
          - type: 'custom:mini-graph-card'
            name: Humidity
            entities:
              - entity: sensor.downstairs_humidity
                name: Downstairs
                show_state: false
              - entity: sensor.upstairs_humidity
                name: Upstairs
                show_state: false
              - entity: sensor.ecobee_outside_humidity
                name: Outside
                show_state: false
            hours_to_show: 24
            points_per_hour: 10
            line_width: 2
          - type: glance
            entities:
              - sensor.moon
              - sun.sun
              - sensor.openskyflights
          # - type: history-graph
          #   title: "Downstairs Temperature"
          #   hours_to_show: 24
          #   entities:
          #     - entity: sensor.ecobee_downstairs_target_temperature
          #       name: Target
          #     - entity: sensor.ecobee_downstairs_current_temperature
          #       name: Actual
          #     - sensor.ecobee_downstairs_state
          #     - sensor.ecobee_downstairs_fan
          # - type: history-graph
          #   title: "Upstairs"
          #   hours_to_show: 12
          #   entities:
          #     - sensor.ecobee_upstairs_target_temperature
          #     - sensor.ecobee_upstairs_current_temperature
          #     - sensor.ecobee_upstairs_state
          #     - sensor.ecobee_upstairs_fan
          - type: history-graph
            title: "Downstairs"
            hours_to_show: 24
            entities:
              - climate.downstairs
          - type:  history-graph
            title: "Upstairs"
            hours_to_show: 24
            entities:
              - climate.upstairs
  - title: F1
    icon: mdi:car-sports
    cards:
      - type: vertical-stack
        cards:
        - type: picture
          image: /local/f1.jpg
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.roku_espn_tap_action
          # tap_action:
            # action: call-service
            # service: media_player.select_source
            # service_data:
            #   entity_id: media_player.50_tcl_roku_tv
            #   source: "ESPN"
        - type: markdown
          content: > 
            ## {{ states.calendar.f1_all.attributes.message }}
              
            {{ ((as_timestamp(states.calendar.f1_all.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

            Start local: {{ states.calendar.f1_all.attributes.start_time}} 

            Start UTC: {{ as_timestamp(states.calendar.f1_all.attributes.start_time)|timestamp_utc}} 

            ## {{ states.calendar.f1_qualifying.attributes.message }}
            
            {{ ((as_timestamp(states.calendar.f1_qualifying.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go
            
            Start local: {{ states.calendar.f1_qualifying.attributes.start_time }}

            Start UTC: {{ as_timestamp(states.calendar.f1_qualifying.attributes.start_time)|timestamp_utc }}

            ## {{ states.calendar.f1_race.attributes.message }}
            
            {{ ((as_timestamp(states.calendar.f1_race.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

            Start local: {{ states.calendar.f1_race.attributes.start_time }}

            Start UTC: {{ as_timestamp(states.calendar.f1_race.attributes.start_time)|timestamp_utc }}
  - title: Commute
    icon: mdi:briefcase
    cards:
      - type: sensor
        entity: sensor.waze_home_to_collins
        name: Collins Commute
        graph: line
  - title: System
    icon: mdi:cog
    cards:
      - type: vertical-stack
        title: People
        cards:
          - type: glance
            entities:
              - binary_sensor.shankar_presence
              - binary_sensor.christine_presence
          - type: 'custom:battery-state-card'
            title: false
            sort_by_level: asc
            entities:
              - entity: sensor.pixel_2_battery_level
                name: 'Pixel 2'
              - entity: sensor.galaxy_s9_battery_level
                name: 'S9'
              - entity: sensor.nexus_7_battery_level
                name: 'Nexus 7'

      - type: vertical-stack
        title: Home Assistant
        cards:
          - type: glance
            entities:
              - sensor.ha_uptime
              - sensor.ha_version
          - type: glance
            show_icon: false
            columns: 3
            entities:
              - entity: sensor.count_binary_sensors
                name: Binary Sensors
              - entity: sensor.count_sensors
                name: Sensors
              - entity: sensor.count_switches
                name: Switches
              - entity: sensor.count_device_trackers
                name: Device Trackers
              - entity: sensor.count_automations
                name: Automations
              - entity: sensor.count_scripts
                name: Scripts
          - type: grid
            title: Ubuntu-Server
            square: false
            columns: 2
            cards:
              - type: 'custom:mini-graph-card'
                align_icon: left
                align_state: center
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - sensor.processor_use_percent
                font_size: 75
                icon: 'mdi:chip'
                name: CPU
                show:
                  fill: false
              - type: 'custom:mini-graph-card'
                align_icon: left
                align_state: center
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - sensor.memory_use_percent
                font_size: 75
                name: Memory
                show:
                  fill: false
              - type: 'custom:mini-graph-card'
                align_icon: left
                align_state: center
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - sensor.disk_use_percent_config
                font_size: 75
                name: Data 
                show:
                  fill: false
              - type: 'custom:mini-graph-card'
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - sensor.processor_temperature
                font_size: 75
                name: Temp 
                show:
                  fill: false
          - type: glance
            columns: 4
            title: false
            show_state: false
            show_header_toggle: false
            entities:
              - entity: zone.home
                icon: 'mdi:home-assistant'
                name: HA
                tap_action:
                  action: call-service
                  service: homeassistant.restart
              - entity: zone.home
                icon: 'mdi:cogs'
                name: Automation
                tap_action:
                  action: call-service
                  service: automation.reload
              - entity: zone.home
                icon: 'mdi:script-text'
                name: Script
                tap_action:
                  action: call-service
                  service: script.reload
              - entity: zone.home
                icon: 'mdi:group'
                name: Groups
                tap_action:
                  action: call-service
                  service: group.reload
              - entity: zone.home
                icon: 'mdi:play'
                name: Start BOINC
              - entity: zone.home
                icon: 'mdi:pause'
                name: 'Stop BOINC'

      - type: vertical-stack
        title: Network
        cards:
          - type: glance
            columns: 3
            show_icon: true
            entities:
              - entity: device_tracker.front_cam
                name: Front Cam
                icon: 'mdi:cctv'
              - entity: device_tracker.back_cam
                name: Back Cam
                icon: 'mdi:cctv'
              - entity: device_tracker.modem
                name: Modem
                icon: 'mdi:router-network'
              - entity: device_tracker.upstairs_wap
                name: Upstairs WAP
                icon: 'mdi:router-wireless'
              - entity: device_tracker.downstairs_wap
                name: Downstairs WAP
                icon: 'mdi:router-wireless'
              - entity: device_tracker.netgear_switch
                name: Switch
                icon: 'mdi:switch'
          - type: grid
            title: Router
            columns: 2
            square: false
            cards:
              - type: 'custom:mini-graph-card'
                name: CPU
                icon: mdi:server
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - entity: sensor.mikrotik_cpu_load
                font_size: 75
                show:
                  fill: false
              - type: 'custom:mini-graph-card'
                name: Memory
                font_size: 75
                show:
                  fill: false
                icon: mdi:memory
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - entity: sensor.mikrotik_memory_usage
              - type: 'custom:mini-graph-card'
                name: HDD
                font_size: 75
                show:
                  fill: false
                icon: mdi:harddisk
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - entity: sensor.mikrotik_hdd_usage
              - type: 'custom:mini-graph-card'
                name: Router KB/s
                font_size: 75
                show:
                  fill: false
                icon: mdi:server
                hours_to_show: 12
                points_per_hour: 10
                entities:
                  - entity: sensor.mikrotik_ether1_tx
                    name: Sent
                  - entity: sensor.mikrotik_ether1_rx
                    name: Received
          - type: grid
            columns: 2
            square: false
            title: Internet
            cards:
              - type: 'custom:mini-graph-card'
                name: ISP Speed
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.speedtest_download
                  - sensor.speedtest_upload
              - type: 'custom:mini-graph-card'
                name: Ping
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.speedtest_ping
          - type: entities
            title: Status
            entities:
              - sensor.duckdns_home
              - sensor.myip
  - title: Docker
    icon: mdi:docker
    cards:
      - type: grid
        title: Docker Status
        columns: 1
        square: false
        cards:
        - type: glance
          entities:
            - entity: sensor.docker_containers_running
              name: Running
            - entity: sensor.docker_containers_paused
              name: Paused
            - entity: sensor.docker_containers_stopped
              name: Stopped
            - entity: sensor.docker_homeassistant_status
              name: HA
            - entity:  sensor.docker_version
              name: Ver
        - type:  horizontal-stack
          cards:
            - type: 'custom:mini-graph-card'
              name: Docker CPU
              hours_to_show: 12
              points_per_hour: 10
              font_size: 75
              show:
                fill: false
              entities:
                - sensor.docker_cpu
            - type: 'custom:mini-graph-card'
              name: Docker Mem
              hours_to_show: 12
              points_per_hour: 10
              font_size: 75
              show:
                fill: false
              entities:
                - sensor.docker_memory

      - type: grid
        columns: 1
        square: false
        title: HA Docker
        cards: 
          - type: entities
            entities:
              - entity: sensor.docker_homeassistant_state
                name: State
              - entity: sensor.docker_homeassistant_status
                name: Status
              # - sensor.docker_homeassistant_up_time
              # - sensor.docker_homeassistant_cpu
              # - sensor.docker_homeassistant_memory
          - type: horizontal-stack
            cards:
              - type: 'custom:mini-graph-card'
                name: HA CPU
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.docker_homeassistant_cpu
              - type: 'custom:mini-graph-card'
                name: HA Mem
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.docker_homeassistant_memory
      - type: grid
        columns: 1
        square: false
        title: Omada Docker
        cards: 
          - type: entities
            entities:
              - entity: sensor.docker_omada_controller_state
                name: State
              - entity: sensor.docker_omada_controller_status
                name: Status
              # - sensor.docker_homeassistant_up_time
              # - sensor.docker_homeassistant_cpu
              # - sensor.docker_homeassistant_memory
          - type: horizontal-stack
            cards:
              - type: 'custom:mini-graph-card'
                name: Omada CPU
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.docker_omada_controller_cpu
              - type: 'custom:mini-graph-card'
                name: Omada Mem
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.docker_omada_controller_memory
      - type: grid
        columns: 1
        square: false
        title: Signal CLI Docker
        cards: 
          - type: entities
            entities:
              - entity: sensor.docker_signalcli_state
                name: State
              - entity: sensor.docker_signalcli_status
                name: Status
              # - sensor.docker_homeassistant_up_time
              # - sensor.docker_homeassistant_cpu
              # - sensor.docker_homeassistant_memory
          - type: horizontal-stack
            cards:
              - type: 'custom:mini-graph-card'
                name: Signal CPU
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.docker_signalcli_cpu
              - type: 'custom:mini-graph-card'
                name: Signal Mem
                hours_to_show: 12
                points_per_hour: 10
                font_size: 75
                show:
                  fill: false
                entities:
                  - sensor.docker_signalcli_memory


