title: Home
custom_header:
  compact_mode: true
  button_text:
    # options: '{{dayNameShort}} {{year4d}}-{{monthNumLZ}}-{{dayNumLZ}}<br>{{ hours24LZ }}:{{ minutesLZ }}'
    options: '{{dayNameShort}} {{monthNameShort}} {{dayNum}}<br>{{hours24LZ}}:{{minutesLZ}}'
swipe_nav:
  wrap: true
  animate: flip
  skip_tabs:
  swipe_amount: 15
views:
  - title: Main
    icon: mdi:home-assistant
    cards:
      - entity: media_player.50_tcl_roku_tv
        type: media-control
      - entities:
        - light.living_room_lamp
        - light.entry_lamp
        - light.bedroom_lamp
        - light.bedroom_ceiling
        - light.bedroom_ceiling_2
        show_header_toggle: true
        title: Lights
        type: entities
      - entity: camera.mjpeg_camera
        type: picture-entity
  - title: Weather
    icon: mdi:weather-sunny
    cards:
      - type: vertical-stack
        cards:
        - type: 'custom:weather-card-chart'
          title: Weather
          weather: weather.openweathermap
        - type: horizontal-stack
          cards:
          - type: picture-entity
            entity: camera.radar_dc_current
          - type: picture-entity
            entity: camera.radar_dc_animated
  - title: F1
    icon: mdi:car-sports
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: > 
            ## {{ states.calendar.f1_all.attributes.message }}
              
            {{ ((as_timestamp(states.calendar.f1_all.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

            Start local: {{ states.calendar.f1_all.attributes.start_time}} 

            Start UTC: {{ as_timestamp(states.calendar.f1_all.attributes.start_time)|timestamp_utc}} 

            ## {{ states.calendar.f1_qualifying.attributes.message }}
            
            {{ ((as_timestamp(states.calendar.f1_qualifying.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go
            
            Start local: {{ states.calendar.f1_qualifying.attributes.start_time }}

            Start UTC: {{ as_timestamp(states.calendar.f1_qualifying.attributes.start_time)|timestamp_utc }}

            ## {{ states.calendar.f1_race.attributes.message }}
            
            {{ ((as_timestamp(states.calendar.f1_race.attributes.start_time) - as_timestamp(now()))/3600) | round(2) }} hours to go

            Start local: {{ states.calendar.f1_race.attributes.start_time }}

            Start UTC: {{ as_timestamp(states.calendar.f1_race.attributes.start_time)|timestamp_utc }}
        - type: picture
          image: /local/f1.jpg
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.roku_espn_tap_action
          # tap_action:
            # action: call-service
            # service: media_player.select_source
            # service_data:
            #   entity_id: media_player.50_tcl_roku_tv
            #   source: "ESPN"
  - title: Commute
    icon: mdi:briefcase
    cards:
      - type: sensor
        entity: sensor.waze_home_to_collins
        name: Collins Commute
        graph: line



