version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/pi/homeassistant:/config
      - /tmp:/tmp
      - /media/usb:/media/usb
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host
