version: "3.5"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    # volumes: 
    # - mosquitto.conf:/mosquitto/config/mosquitto.conf
