---
version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-armhf  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - /home/pi/motioneye:/etc/motioneye
      - /media/usb/motioneye:/var/lib/motioneye
    restart: always
    environment:
      - TZ=America/New_York

# volumes:
#   etc_motioneye:
#   var_lib_motioneye:
