---
version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-armhf  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - etc_motioneye:/home/pi/motioneye
      - var_lib_motioneye:/home/pi/motioneye/lib/motioneye

volumes:
  etc_motioneye:
  var_lib_motioneye:
