version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - "8080:8080" # map docker port 8080 to host port 8080.
    network_mode: "host"
    volumes:
      - "/home/pi/signal-cli-config:/home/.local/share/signal-cli" # map "signal-cli-config" folder 
